# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tree_select}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stijn (stijnster) Mathysen", "Rails 3 patch Szymon (jeznet) Je\305\274"]
  s.date = %q{2010-05-18}
  s.description = %q{tree_select as a gem}
  s.email = %q{szymon@jez.net.pl}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENCE",
     "README",
     "init.rb",
     "lib/tree_select.rb",
     "tree_select.gemspec"
  ]
  s.homepage = %q{http://jeznet@github.com/jeznet/tree_select}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{tree_select as a gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

